name: CI
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  pull_request:
    branches: [master]
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - name: Install Packages
        run: npm install
      - name: Building App
        run: npm run bundle
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build 
        